<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ATTLIST project n_mipmap_threads NMTOKEN #REQUIRED>
	<!ELEMENT anything EMPTY>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Project"
		unuid="1407538799771.364800810.1138556591"
		mipmaps_folder="trakem2.1407538799771.364800810.1138556591/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
		n_mipmap_threads="8"
	>
	</project>
	<t2_layer_set
		oid="3"
		width="0.0"
		height="0.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top level"
		links=""
		layer_width="2868.0"
		layer_height="6512.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="1.0"
			pixelHeight="1.0"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="pixel"
		/>
		<t2_layer oid="4"
			 thickness="0.0"
			 z="0.0"
			 title=""
		>
			<t2_patch
				oid="5"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997315,-0.004037,-0.00416,0.985689,1495.117382,5.550203)"
				title="0.0-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_0_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="6"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99731,-0.004061,-0.00492,0.98555,1494.142544,853.565701)"
				title="0.1-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_1_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="7"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997778,-0.00333,-0.00214,0.986685,1492.703338,1699.129804)"
				title="0.2-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_2_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="8"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99788,-0.002076,-0.00385,0.988166,1493.581852,2543.375755)"
				title="0.3-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_3_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="9"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.998072,-0.001524,-0.003769,0.996668,1492.856626,3394.385647)"
				title="0.4-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_4_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="10"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.998541,-7.51E-4,-0.005571,0.996412,1492.874615,4251.214312)"
				title="0.5-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_5_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="11"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.998895,-8.3E-5,-0.005278,0.999572,1491.267878,5106.666219)"
				title="0.6-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_6_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="12"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997105,0.00284,-0.005581,0.999002,349.07099,5107.585615)"
				title="0.7-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_7_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="13"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997129,0.002537,-0.005338,0.995888,350.259527,4253.818545)"
				title="0.8-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_8_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="14"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.996992,0.001629,-0.004575,0.995574,351.172241,3400.792728)"
				title="0.9-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_9_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="15"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.996721,5.89E-4,-0.004328,0.987192,351.98607,2551.157831)"
				title="0.10-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_10_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="16"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.996434,-0.001022,-0.001711,0.984636,350.220796,1705.974372)"
				title="0.11-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_11_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="17"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.996889,-0.003288,-0.004726,0.985048,351.280302,862.33498)"
				title="0.12-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_12_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="18"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.997051,-0.002465,-0.004406,0.985689,352.282752,13.485779)"
				title="0.13-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/A1_13_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="19"
			 thickness="0.0"
			 z="1.0"
			 title=""
		>
			<t2_patch
				oid="20"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99901,0.033963,-0.026781,1.00113,1377.454312,183.642825)"
				title="1.0-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_0_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="21"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999523,0.033372,-0.027511,0.992337,1357.447616,1043.519748)"
				title="1.1-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_1_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="22"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999695,0.032268,-0.024599,0.998246,1336.726965,1894.549842)"
				title="1.2-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_2_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="23"
				width="1376.0"
				height="1040.0"
				transform="matrix(1.000016,0.030983,-0.026854,0.997767,1318.941062,2748.904589)"
				title="1.3-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_3_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="24"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999969,0.030302,-0.025102,1.002335,1298.845283,3611.424917)"
				title="1.4-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_4_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="25"
				width="1376.0"
				height="1040.0"
				transform="matrix(1.000147,0.029503,-0.025267,1.002447,1280.349376,4474.671828)"
				title="1.5-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_5_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="26"
				width="1376.0"
				height="1040.0"
				transform="matrix(1.000296,0.028675,-0.025133,1.004902,1261.819551,5334.446615)"
				title="1.6-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_6_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="27"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999503,0.027589,-0.025292,1.004972,118.147562,5307.326315)"
				title="1.7-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_7_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="28"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999173,0.028112,-0.024804,1.003192,136.723169,4446.974619)"
				title="1.8-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_8_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="29"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999315,0.028877,-0.024913,1.003524,155.106313,3582.898256)"
				title="1.9-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_9_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="30"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999684,0.029523,-0.026699,0.998488,175.032825,2726.707246)"
				title="1.10-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_10_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="31"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999672,0.030022,-0.024279,0.999558,192.528142,1864.162426)"
				title="1.11-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_11_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="32"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.999453,0.031444,-0.027436,0.99423,213.684548,1010.899963)"
				title="1.12-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_12_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="33"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99925,0.030783,-0.026838,1.000098,234.015234,149.394462)"
				title="1.13-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/B1_13_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="34"
			 thickness="0.0"
			 z="2.0"
			 title=""
		>
			<t2_patch
				oid="35"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.993708,0.048744,-0.049981,0.998266,1427.587772,252.469243)"
				title="2.0-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_0_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="36"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.993911,0.048853,-0.050961,0.992536,1388.438152,1102.659231)"
				title="2.1-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_1_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="37"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.993781,0.048328,-0.046887,0.997233,1346.469027,1963.014967)"
				title="2.2-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_2_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="38"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.993543,0.048385,-0.049896,0.997036,1309.505128,2817.39215)"
				title="2.3-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_3_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="39"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994083,0.049159,-0.048405,1.002761,1269.264383,3675.980075)"
				title="2.4-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_4_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="40"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994453,0.049341,-0.049902,1.002223,1230.836606,4534.752753)"
				title="2.5-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_5_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="41"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99471,0.049588,-0.048385,1.003613,1190.743747,5399.86908)"
				title="2.6-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_6_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="42"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994675,0.04781,-0.048279,1.003522,50.161494,5349.744095)"
				title="2.7-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_7_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="43"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.99436,0.047694,-0.050124,1.002143,90.466336,4484.691121)"
				title="2.8-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_8_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="44"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994575,0.047645,-0.048975,1.00229,129.022823,3626.454924)"
				title="2.9-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_9_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="45"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994695,0.048526,-0.049348,0.997169,168.903405,2766.250914)"
				title="2.10-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_10_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="46"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994681,0.049061,-0.047197,0.998002,205.816777,1911.557028)"
				title="2.11-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_11_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1376"
				o_height="1040"
				min="0.0"
				max="255.0"
				mres="32"
			>
			</t2_patch>
			<t2_patch
				oid="47"
				width="1376.0"
				height="1040.0"
				transform="matrix(0.994662,0.049362,-0.051177,0.992641,247.686233,1054.411356)"
				title="2.12-1"
				links=""
				type="0"
				file_path="/groups/apig/tomo/DEMO/TIF/C1_12_2.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"